#!/bin/bash
# Quick Start Guide for AI Document Intelligence RAG Pipeline

echo "========================================"
echo "AI Document Intelligence - Quick Start"
echo "========================================"
echo ""
echo "Prerequisites:"
echo "  1. Ollama running: ollama serve"
echo "  2. Llama 3.2 3B installed: ollama pull llama3.2:3b"
echo ""
echo "Step 1: Activate virtual environment"
echo "  source .venv/bin/activate"
echo ""
echo "Step 2: Start API server"
echo "  uvicorn app.main:app --reload"
echo ""
echo "Step 3: Test the API (in another terminal)"
echo ""
echo "  a) Health check:"
echo "     curl http://localhost:8000/health"
echo ""
echo "  b) Ingest text:"
echo "     curl -X POST http://localhost:8000/ingest/text \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"text\": \"Your text here\", \"source\": \"doc1\"}'"
echo ""
echo "  c) Ask question:"
echo "     curl -X POST http://localhost:8000/query \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"question\": \"What is the topic?\"}'"
echo ""
echo "  d) Interactive API docs:"
echo "     Open browser to: http://localhost:8000/docs"
echo ""
echo "========================================"
echo "Project Structure"
echo "========================================"
echo "app/"
echo "  ├── main.py               ← FastAPI endpoints"
echo "  ├── pipeline.py           ← RAG orchestration (NEW)"
echo "  ├── generation/"
echo "  │   └── rag.py           ← Ollama/Llama (UPDATED)"
echo "  ├── ingestion/"
echo "  │   ├── pdf_processor.py ← PDF extraction"
echo "  │   └── chunker.py       ← Text chunking"
echo "  └── retrieval/"
echo "      ├── embedder.py      ← SentenceTransformer"
echo "      └── vector_store.py  ← FAISS storage"
echo ""
echo "test_pipeline.py           ← Component tests"
echo "test_integration.py        ← End-to-end tests"
echo "test_api.py               ← API endpoint tests"
echo "README.md                 ← Full documentation"
echo "IMPLEMENTATION.md         ← Implementation details"
echo ""
echo "========================================"
echo "Testing"
echo "========================================"
echo ""
echo "Test components (no Ollama needed):"
echo "  python test_pipeline.py"
echo ""
echo "Test end-to-end with Ollama:"
echo "  python test_integration.py"
echo ""
echo "Test API endpoints:"
echo "  python test_api.py"
echo ""
echo "========================================"
